modLoader="javafml"
loaderVersion="[36,)"
license="The Unlicense"

[[mods]]
	modId="zeboncraft"
	version="${file.jarVersion}"
	displayName="ZebonCraft"
	# logoFile="zeboncraft.png"
	credits="Thank Sekwah for this one. *Stares*"
	authors="HardCoded"
	description='''
	Very long. Not so compact. But very nice.
	
	https://www.twitch.tv/hard_coded
	'''

[[dependencies.zeboncraft]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.zeboncraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"